version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/loa-manager/src
    env_file:
      - ./.env
    ports:
      - 3000:3000

  database:
    image: mongo:6
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
